### ISSUE TITLE
Sprite CSS

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#17]
Per ridurre il numero di chiamate e di file nella cartella Images si possono usare un po' di magia "Made in Penaz™" e CSS

**Comment by Penaz91** [comment]
Se vogliamo usare un solo file per tutte le icone, dobbiamo convertire le SVG in PNG perdendo la scalabilità di queste ultime.
Purtroppo le magie di CSS/SVG sono solo possibili in HTML5.

**Comment by Aronoele20395** [comment]
e allora niente, non complichiamoci ancora la vita.

**Comment by Penaz91** [comment]
Penso però sia il caso di fare un minimo di pulizia nella cartella "Images" magari separando le foto dalle icone (Niente di pauroso)
