### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#22]
Creazione di un'icona grande almeno 310x310 pixel e che sia riconoscibile ad una grandezza di 16x16 pixel da usare come favicon per i bookmark e le tab. Alla conversione poi ci penso io

**Comment by Aronoele20395** [comment]
Yup, ci penso io. Me l'avevi gia' detto ma me lo ero completamente dimenticata, sorry.

**Comment by Penaz91** [comment]
Per questo esistono le issue.
Anticipo di SWE: **Tracciamento** :stuck_out_tongue_closed_eyes:

**Comment by Aronoele20395** [comment]
Icona fatta e caricata, dichiarerei la issue chiusa.

**Comment by Penaz91** [comment]
Ok, la trasformo, la provo e provvedo

**Comment by Penaz91** [comment]
Confermata funzionante sui browser comuni. Chiudo
