### ISSUE TITLE
Firefox Richiama onBlur() senza disattivare il field

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#23]
Creando una situazione in cui il testo viene preso come testo e non come placeholder.

**Comment by Rei2229** [comment]
Direi che visto che si tratta a quanto pare di un comportamento "Sbagliato" da parte di uno specifico Browser si può giustificare in sede di relazione

**Comment by Rei2229** [comment]
Ne ho parlato anche con Andrea. Mi ha detto che anche secondo lui è semplicemente un criterio che ha Firefox (diverso da quello di Chrome) non per questo sbagliato. Insomma alla fine ogni Motore di ricerca fa un po' il cazzo che vuole lo sappiamo
