### ISSUE TITLE
Fix CSS media='screen' per campi troppo lunghi e disallineati

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#28]
Se i campi vanno a capo, le label diventano orribili.

Dobbiamo decidere se accettare questo horror oppure accettare campi che normalmente sarebbero non allineati verticalmente e vivere così

**Comment by Penaz91** [comment]
Esempio del baco (sito nella metà sinistra dello schermo)
![screen](https://user-images.githubusercontent.com/6682630/35296448-52fe4828-007c-11e8-9d93-6b678701656f.png)

**Comment by Aronoele20395** [comment]
Ho fatto un tentativo sulla pagina dello screenshot qui sopra. @Penaz91 se volessi verificare il risultato poi vedo se applicarlo a tutte le pagine.

**Comment by Penaz91** [comment]
Appena finisco con questo JS ci provo

**Comment by Penaz91** [comment]
Non risolto, annulla i cambiamenti per favore
![screen](https://user-images.githubusercontent.com/6682630/35618264-bc13ea3a-067a-11e8-9179-e0a5429ee570.png)

**Comment by Aronoele20395** [comment]
Cosa abbiamo deciso di fare a riguardo? Teniamo l'horror?

**Comment by Rei2229** [comment]
Come avevo scritto in precedenza purtroppo c'e' da fare una scelta. A sto punto forse e' meglio avere una visione ottimale a schermo intero (che e' dopotutto la situazione normale) piuttosto che un compromesso che lascia tutti insoddisfatti. Io terrei all'ineamento a dx come da originale, al massimo l'allineamento al centro (come dovrebbe erssere ora dopo la mia commit).

**Comment by Penaz91** [comment]
Sarebbe cosa buona e giusta tenere i campi e le label ad una certa
percentuale dello schermo piuttosto che in em
Questo mitigherebbe il problema ed eviterebbe che i campi vadano a
tagliarsi su schermi piú piccoli

Il 01 feb 2018 11:57 PM, "Rei2229" <notifications@github.com> ha scritto:

**Comment by Penaz91** [comment]
Forse l'ho fixato, questo accade tipo 5 pixel prima della commutazione a mobile:
![screen](https://user-images.githubusercontent.com/6682630/35855017-44051c46-0b32-11e8-93d1-09c80a45613c.png)

**Comment by Penaz91** [comment]
Visuale a pieno schermo:
![screen](https://user-images.githubusercontent.com/6682630/35855053-5deca9bc-0b32-11e8-9757-764f22b29400.png)

**Comment by Penaz91** [comment]
In mobile:
![screen](https://user-images.githubusercontent.com/6682630/35855093-7ae7c6a0-0b32-11e8-821e-edcf96f21974.png)

**Comment by Aronoele20395** [comment]
Grande! Io sono scema e me ne accorgo ora ma... ottimo!

**Comment by Penaz91** [comment]
Penso questo possa essere chiuso, lascio a @Fomodei94 il compito di strizzare materiale da Relazione (compresi limiti delle nostre scelte, come richiesto dalle slide di consegna)
