### ISSUE TITLE
Descrizioni aggiuntive Form

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#29]
Ovviamente in caso di mancanza di Javascript (anche se praticamente ce l'hanno pure le caffettiere) non possiamo fare affidamento su placeholder che diano istruzioni su come compilare i form. È necessario (e vitale ai fini dell'accessibilità) inserire delle descrizioni/istruzioni statiche, anche tramite caption/title.

**Comment by Penaz91** [comment]
Mancano le istruzioni riguardo la modifica dei dati personali (struttura_userpanel_account.html)

**Comment by Penaz91** [comment]
verificadisp:
"panneLo utente"
Sarebbe meglio specificare di controllare che lo strumento selezionato sia quello giusto e che se si vuole si può cambiare
Inoltre sarebbe meglio avvisare l'utente che la pagina verrà ricaricata quando viene cliccato "Verifica Disponibilità"
La sezione "Pannello Utente" è nel menu di sinistra, non sopra (secondo me)

**Comment by Penaz91** [comment]
prenotazione_sala:
Bene, ma ancora una volta, l'utente dovrebbe sapere che la pagina viene ricaricata con pezzi nuovi dopo aver cliccato su "Verifica disponibilità".
Per noi è ovvio, ma per l'utente no.
Il resto "Me par bøn"

**Comment by Penaz91** [comment]
roombooksearch.php:
"si eFettua"
Il resto bene, ma non benissimo. Mi sembra che l'insieme di istruzioni sia un po' condensato se messo tutto assieme e poco comprensibile. Ma forse è questione mia personale.

**Comment by Penaz91** [comment]
instrumentbooksearch.php
Stesse considerazioni riguardo la condensazione delle istruzioni

aggiungiSala.php
Mai fare riferimento ai campi per valori posizionali (Primo, secondo, ecc...) usa piuttosto i nomi delle `<label>`. Le persone che usano screenreader e che vanno a navigare non linearmente potrebbero non avere il nostro esatto concetto di "prima" e "dopo"

searchEditRoom.php:
"ad eZ:"
Si applicano i criteri di "condensatezza" visti sopra

**Comment by Penaz91** [comment]
aggiungiStrumentazione.php
Tutto bene, l'alternativa testuale non viene solo visualizzata nel caso l'immagine non sia disponibile, ma è letta anche dagli screenreader

searchEditInstruments.php
Tutto bene, si applicano i criteri di "condensatezza" di cui sopra.

Con questo dovrei aver finito

**Comment by Aronoele20395** [comment]
Fatto. Pushato. Se volete ricontrollare....
