### ISSUE TITLE
Miglioramento criteri di ricerca

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#32]
In caso di prezzi sarebbe carino avere 3 criteri di ricerca
- Prezzo Almeno x€
- Prezzo Al massimo x€
- Prezzo esatto

**Comment by Aronoele20395** [comment]
Vero, sarebbe carino ma diventa utile se mettiamo -che so- cinque (che secondo me sarebbe ancora un numero troppo basso) chitarre diverse noleggiabili

**Comment by Penaz91** [comment]
Non è troppo difficile da implementare, quindi non mi lamento se lo devo fare

**Comment by Aronoele20395** [comment]
Io direi che lo teniamo come "cosa da fare se ci resta tempo alla fine"



(si', lo so che fa ridere)
