### ISSUE TITLE
404 SuperFigo 9000

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#34]
È possibile creare una pagina di 404 in PHP usando $_SERVER['request_uri'] per avere un 404 attivo che cerca le pagine più simili per nome ad esempio, rendendo più difficile perdersi dato che gli errori di digitazione sono comuni ma risolvibili in questo modo.

Ovviamente questo richiederebbe una modifica del .htaccess di Apache, ma la sola presenza di questo potrebbe darci punti in più, con la scusa dell'accessibilità

**Comment by Penaz91** [comment]
Idea di clipart per dare l'idea dell'ira del server nel non trovare la pagina:
https://openclipart.org/detail/274669/breaking-ground-with-guitar-silhouette

**Comment by Rei2229** [comment]
L'idea del 404 figo ci sta. Ho seguito solo una lezione di WIM ma marchiori ha parlato proprio di questo. L'ideale sarebbe avere una pagina 404 divertente ma che allo stesso tempo non solo ti dia la possibilità di tornare alla home, ma ti offra anche qualche servizio del sito. Tipo:
404-figo +
Tona alla Home
Vuoi prenotare delle sale? Clicca qui
Vuoi noleggiare strumentazione?
(Barra di ricerca?) //Semmai vorremmo metterla.
Insomma non solo un semplice 404 che (And I quote) "Ti prenda per il coppino riportandoti all'ingresso"

**Comment by Aronoele20395** [comment]
Concordo con Luca se il tutto non diventa troppo complesso

**Comment by Penaz91** [comment]
@Rei2229 Qualcosa del genere?
![untitled](https://user-images.githubusercontent.com/6682630/35110796-f7113d50-fc79-11e7-87ae-7a3312b5ef9e.png)

**Comment by Penaz91** [comment]
Messa un'idea per un 404 base, richiede molto lavoro di CSS

**Comment by Penaz91** [comment]
Non so se convenga lavorare in PHP sull'uri dato che comunque le pagine interessanti sono poche.

**Comment by Aronoele20395** [comment]
Posso lavorare al css da domani se c'è bisogno. Oggi giornata in famiglia e non riuscirò a fare cose

**Comment by Aronoele20395** [comment]
![schermata del 2018-01-25 21-18-26](https://user-images.githubusercontent.com/35222366/35434763-8ca886e8-0288-11e8-919f-669b2367f689.png)
![schermata del 2018-01-25 21-12-35](https://user-images.githubusercontent.com/35222366/35434765-8d0f5eb8-0288-11e8-9cdc-1d4687051600.png)

Queste sono le due prove che sono state fatte. Io personalmente penso che a quella più chiara manchi qualcosa e quella più scura non si distingua bene. 
Io pensavo che un'idea potrebbe essere fare la cassetta nera con bordo arancione (probabilmente sarà un pugno in un occhio). Voi cosa ne pensate? 
Se avete alternative ben venga!

**Comment by Rei2229** [comment]
A me quella chiara non dispiace affatto, se non ci sono problemi di contrasti in  sede di accessibilità io la voterei come scelta definitiva. La cassetta nera con bordo arancione così ad immaginazione pare anche a me un pugno in un occhio

**Comment by Fomodei94** [comment]
Secondo me la chiara è già figa così! Si potrebbe provare con un bordino di 1px arancione (anche nero forse evidenzia e non è un pugno in un occhio), bisognerebbe vederlo ma di base per me, se sorgono problemi con i bordi, è già figo così quello chiaro!

**Comment by Penaz91** [comment]
A me la chiara non dispiace, in ogni caso a me non ci vuole nulla per mettere un bordo arancione.
In ogni caso ho ancora anche quella della chitarra.

**Comment by Aronoele20395** [comment]
Pushato quella chiara, si fa sempre in tempo a cambiare. 
Per ora va bene così.
