### ISSUE TITLE
Rinnovo Pannello Amministrativo

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#35]
Che valga la pena cambiare il pannello amministrativo in modo che ogni pulsante assuma questa forma?

![panel](https://user-images.githubusercontent.com/6682630/35100857-9bfe7214-fc5d-11e7-9bc9-e9953bee5cd5.png)

**Comment by Fomodei94** [comment]
Per me ci può stare!

**Comment by Rei2229** [comment]
Per me ci può stare se non comporta troppo lavoro/tempo. L'idea di base è carina, sarebbe bello ma al momento direi di dare priorità ad altro. Se alla fine ci avanza tempo sarebbe un miglioramento a cui pensare seriamente

**Comment by Aronoele20395** [comment]
Vediamo come viene, finche' ne vediamo uno solo puo' starci ma poi magari mettendoli tutti diventa pesante (alla vista, intendo)

**Comment by Penaz91** [comment]
@Rei2229 Guarda, il lavoro comportato è circa 1 oretta, compreso il PHP per i conteggi ed il CSS per i bottoni.

**Comment by Rei2229** [comment]
@Penaz91 perchè sei tu ;)

**Comment by Penaz91** [comment]
Versione alternativa pushata in un altro branch. Fate quello che volete
