### ISSUE TITLE
Commenti sulla Relazione

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#4]
## Il layout non è un 3 pannelli standard.
Il 3 pannelli standard prevede una header larga tutta la pagina, con sidebar e contenuto sotto. Il tutto scorre senza elementi fissati.

## Inglese Sarebbe Figo
Se riesci a farlo, io ci sto. Magari potei usare PHP per impostare una variabile e caricare dinamicamente il linguaggio scelto

## NavHelper e TabIndex
Si, ma no. Cioè si lo faremo ma non è pronto xD

## I colori non sono web safe
Purtroppo come sfondo della pagina principale usiamo #111111 che non è websafe. Il resto mi sembra a posto.

**Comment by Fomodei94** [comment]
- [ ] Aggiungere gli strumenti utilizzati nella sezione "Organizz. interna"
- [ ] Tradurre in inglese
- [ ] Modificare descrizione layout a 3 pannelli

**Comment by Aronoele20395** [comment]
Lo sfondo della pagina principale (credo ti riferisca al contenuto) NON e' definitivo, mi devo mettere a farlo.

**Comment by Aronoele20395** [comment]
Per quanto riguarda il colore dello sfondo di cui sopra, io e @Penaz91 abbiamo fatto un paio di tentativi veloci per giungere alla conclusione che con colori web safe il sito è... abbastanza brutto. Quindi se concordate anche voi, @Fomodei94 @Rei2229, ce ne sbattiamo di quell'unico colore che da qualcuno potrebbe essere visto come nero piuttosto che grigio scuro e basta.

**Comment by Rei2229** [comment]
Concordo al 100%. Ce ne sbattiamo di quell'unico colore

**Comment by Penaz91** [comment]
concordo

**Comment by Penaz91** [comment]
Le breadcrumb non hanno veramente una posizione fissa, ma scorrono con la pagina fino a quando toccano la cima, dopodichè passano a posizione fissa. Questa feature è disponibile solo nei browser più moderni: Chome 1.0+, Firefox 1.0+, Safari 1.0+ (Tramite estensione -webkit-sticky), Opera 4.0+, IE/Edge 16+

**Comment by Penaz91** [comment]
La relazione riporta ancora l'uso di "Safe Colors"
Manca l'indirizzo in prima pagina.
Come strumenti puoi aggiungere:
- NeoVIM (Il mio editor)
- Geany (L'editor di Ele e Luca se non erro)
- MariaDB per Il Database (anche no, dato che è già nominato)

**Comment by Aronoele20395** [comment]
E non dimentichiamo Gimp e l'editor di Dani,  ahahah xD

**Comment by Aronoele20395** [comment]
Ci sono un paio di cosucce da sistemare:
- I link alle note non funzionano (o almeno io vengo rimandata alla pagina iniziale al click, non alla nota  a piè di pagina);
- Le breadcrumbs non hanno davvero una posizione fissa come dice anche Dani un paio di commenti più su;
- Quando si parla del database, manca da dire che mantiene anche le informazioni sulla strumentazione noleggiabile (si parla di tener traccia dei noleggi effettuati dagli utenti ma non della strumentazione "fisica");
- Il commento sulla 404 mi ha scaldato il cuore;
- Preciserei che quell'unico colore web safe non influenza in alcun modo la comprensibilità del tutto;
- Preciserei che è stata pensata un'alternativa alle lightboxes in caso di mancanza di Javascript;
- Non mi merito un pochino pochino di html anche io? :(

**Comment by Penaz91** [comment]
Ricordo a Fede che perchè funzionino i link dell'indice e delle note a fondo pagina, bisogna ricompilare il documento LaTeX 2 volte, altrimenti non vanno.

**Comment by Aronoele20395** [comment]
Da aggiungere: livello AAA (WCAG)

**Comment by Penaz91** [comment]
Ho lasciato delle menzioni per @Fomodei94

**Comment by Aronoele20395** [comment]
Alla luce dell'ennesima revisione direi: 
- si dice che vengono lasciati dei link a pagine esterne per le spiegazioni ma non si fa riferimento al mini glossario scritto da Dani;
- la frase "Breadcrumbs che scorrono insieme al contenuto della pagina ma quando ne
raggiungono l’estremità superiore diventano fisse" mi sembra migliorabile, una cosa del tipo "Breadcrumbs che scorrono insieme al contenuto fino a raggiungere l'estremità superiore della pagine dove la posizione diventa fissa"?
- questa frase "nei browser più datati le breadcrumbs scorrono normalmente" richiede un ; (punto e virgola) prima ed un . (punto) dopo;
- c'è uno screenshot in cui ci sono tre "versione inglese" ed uno con due, ne siamo consapevoli?

**Comment by Penaz91** [comment]
In attesa di riscontri

**Comment by Penaz91** [comment]
Addio, e grazie per tutto il pesce
