### ISSUE TITLE
Feedback Operazioni

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#41]
Non tutte le operazioni restituiscono un feedback (alcune eliminazioni, per esempio). il che potrebbe essere un peso sull'accessibilità.

- [x] tasto "noleggia"
- [x] "rendi amministratore"
- [x] "utente non trovato" (style)
- [ ] trova prenotazione
- [x] trova noleggio (appare tabella)
- [x] Tuoi noleggi (appare tabella)
- [x] Tue prenotazioni (appare tabella)
- [ ] Altre apparizioni di tabelle misteriose
- [x] Eliminazione utente (admin)
- [x] Eliminazione noleggio (admin)
- [x] Eliminazione prenotazione (admin)
- [x] Eliminazione noleggio (proprio)
- [x] Eliminazione prenotazione (proprio)

**Comment by Aronoele20395** [comment]
Di questo credo di potermene occupare io, al massimo vi chiedo aiuto

**Comment by Penaz91** [comment]
Nessuna apparizione trovata finora, chiudo
