### ISSUE TITLE
Miglioramento Pannello Utente

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#43]
Le ricerche automatiche del pannello utente (Tue prenotazioni e tuoi noleggi) sono molto scarne e potrebbero aver bisogno di un po' di vivacità e testo.

**Comment by Aronoele20395** [comment]
![schermata del 2018-02-05 16-22-20](https://user-images.githubusercontent.com/35222366/35812271-c1998306-0a90-11e8-85fa-a2b2269547c8.png)

Opinioni please che poi si chiude con sta cosa :)

**Comment by Penaz91** [comment]
Me par bøn
