### ISSUE TITLE
Miglioramenti Pannello Amministrativo

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#44]
Praticamente l'issue #43, ma per il pannello amministrativo

**Comment by Penaz91** [comment]
Non penso questo sia il comportamento inteso
![screen2](https://user-images.githubusercontent.com/6682630/35727992-677b878a-080a-11e8-8452-3a0d947ab16d.png)
![screen](https://user-images.githubusercontent.com/6682630/35727997-69bad9e2-080a-11e8-9422-3b10cd20758b.png)

**Comment by Aronoele20395** [comment]
L'ho scritto ieri sera sul gruppo: non guardate quella pagina, è ancora in cantiere

**Comment by Penaz91** [comment]
Me n'ero dimenticato, scusa
