### ISSUE TITLE
Aggiornamento Traduzioni

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#46]
@Fomodei94 Hai voglia di fare un po' di lavoro traduttivo o preferisci aspettare per ora?

**Comment by Fomodei94** [comment]
A piena disposizione Dani!

**Comment by Penaz91** [comment]
Puoi iniziare a tradurre ciò che c'è nel file "messages.php", basta che prendi l'array associativo MESSAGES_IT, lo copi/incolli nello stesso file, rinomini quello copiato con MESSAGES_EN e traduci. Ce n'è una versione vecchia sotto che puoi eliminare dopo che l'hai presa come esempio.

**Comment by Penaz91** [comment]
Fomodei94.call("Translate", "message.php", update=true)

:stuck_out_tongue_closed_eyes:

**Comment by Aronoele20395** [comment]
Cose da fare: Longdesc in inglese

**Comment by Aronoele20395** [comment]
- [x] home
- [x ] login
- [x ] registrazione
- [x ] cosa offriamo
- [x ] contatti
- [x ] struttura generale


N.B.: Non ho tradotto le longdesc di nessuna pagina.

**Comment by Aronoele20395** [comment]
##TRADUZIONE TESTI
- [ ] accesso_negato.html
- [ ] contenuto_aggiungisala.html
- [x] contenuto_contatti.html
- [x] contenuto_cosaoffriamo.html
- [ ] contenuto_definizioni.html
- [x] contenuto_home.html
- [ ] contenuto_modificasala.html
- [ ] contenuto_modificaStrumenti.html
- [ ] contenuto_noleggio.html
- [ ] contenuto_prenotazioni.html
- [ ] contenuto_privacy.html
- [ ] contenuto_ricercaNoleggi.html
- [ ] contenuto_ricercaPrenotazioni.html
- [ ] contenuto_risultatiprenotazioni.html
- [ ] contenuto_upload.html
- [ ] contenuto_verificaDisp.html
- [ ] form_prenotazione2.html
- [ ] instrumentsearchtable.html
- [ ] lightbox.html
- [ ] menu.html
- [ ] registrazione_ok.html
- [ ] registrazione_ko.html
- [ ] riquadro_strumento.html
- [ ] roomBookTable.html
- [ ] roomSearchTable.html
- [ ] roomsearchtable_admin.html
- [ ] sitemap_admin.html
- [ ] sitemap_main.html
- [ ] sitemap_userpanel.html
- [x] struttura.html
- [ ] struttura50x_.html
- [ ] struttura_404.html
- [ ] struttura_adminpanel.html
- [ ] struttura_aggiungiStrumentazione.html
- [ ] strutturaEliminazione.html
- [x] strutturalogin.html
- [x] strutturaregistrazione.html
- [ ] struttura_searchEditInstruments.html
- [ ] struttura_searchEditRoom.html
- [ ] struttura_searchEditUser.html
- [ ] struttura_userpanel.html
- [ ] struttura_userpanel_account.html
- [ ] tabella_ricercaNoleggi.html
- [ ] usersearchtable.html
- [ ] verificaDisp_parte2.html
- [ ] CARTELLA longdesc

##CAMBIO FILE SORGENTE
- [ ] 404.php
- [ ] 50x.php
- [ ] admin.php
- [ ] confermaEliminazione.php
- [ ] contatti.php
- [ ] definizioni.php
- [ ] index.php
- [ ] instrumentBookSearch.php
- [ ] login.php
- [ ] modificaSala.php
- [ ] modificaStrumentazione.php
- [ ] noleggio.php
- [ ] prenotazione_sala.php
- [ ] privacy.php
- [ ] registrazione.php
- [ ] roomBookSearch.php
- [ ] sale.php
- [ ] searchEditInstruments.php
- [ ] searchEditRoom.php
- [ ] searchEditUser.php
- [ ] sitemap.php
- [ ] uploadImg.php
- [ ] userInstrumentRentals.php
- [ ] userpanel_account.php
- [ ] userpanel.php
- [ ] userInstrumentRentals_admin.php
- [ ] userRoomBookings_admin.php
- [ ] userRoomBookings.php
- [ ] verificaDisp.php

**Comment by Penaz91** [comment]
Nota a margine per me: searchEditInstruments per ora Esplode male in inglese

**Comment by Penaz91** [comment]
Potete per favore controllare le versioni inglesi delle pagine dedicate ad aggiunta, modifica e ricerca di sale e noleggi?

**Comment by Penaz91** [comment]
Tradotto i pezzi che mancano dopo le ultime modifiche. Chiedo conferma per chiusura di questo LUUUUNGO ticket

**Comment by Penaz91** [comment]
Fixato e chiuso
