### ISSUE TITLE
Miglioramento aspetto Login e Registrazione

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#48]
Login e registrazione non sono proprio il massimo dello stile.

Inoltre i campi creati da JavaScript non hanno alcuno stile.

**Comment by Aronoele20395** [comment]
Lo stesso valeva per le pagine di noleggio/prenotazione (la parte delle form). Ora quelle dovrebbero essere a posto.

**Comment by Aronoele20395** [comment]
![schermata del 2018-01-26 18-00-36](https://user-images.githubusercontent.com/35222366/35451255-ec8ca870-02c2-11e8-96c0-d753f5f3943d.png)
![schermata del 2018-01-26 18-00-24](https://user-images.githubusercontent.com/35222366/35451266-f370b5fa-02c2-11e8-9855-0d089aaf667c.png)

Io, sinceramente, sono ad un punto che non so più che modifiche fare. Idee? Va bene così?

**Comment by Penaz91** [comment]
L'aspetto della scrollbar dipende dal toolkit con cui il browser è costruito.
Forse sarebbe meglio ridurre il margin-top del logo nella registrazione per guadagnare qualche pixel

**Comment by Rei2229** [comment]
Direi anche io di ridurre il margin-top. E magari rendere un po' piu' grande il logo. Per il resto penso vada piu' che bene

**Comment by Aronoele20395** [comment]
![schermata del 2018-01-26 18-15-55](https://user-images.githubusercontent.com/35222366/35451886-fede6a16-02c4-11e8-8a5a-b39efe9b758b.png)

**Comment by Aronoele20395** [comment]
@Fomodei94 manca solo la tua risposta. Se ti piace il risultato, chiudi pure la issue.

**Comment by Fomodei94** [comment]
Per me rasenta la perfezione direi! Procedo alla chiusura
