### ISSUE TITLE
Piccoli problemi con TOP

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#49]
Il bottone top ha il piccolo problema che solo la scritta "TOP" è cliccabile, sarebbe molto meglio che tutto il bottone fosse cliccabile (come ho fatto per le voci di menu).

L'area ridotta cliccabile potrebbe confondere l'utente.

**Comment by Rei2229** [comment]
Si lo sapevo già visto che l'effetto grafico è realizzato tramite l'uso di border.
Il fatto è che proprio per come è realizzato chiaramente non è cliccabile e non penso sia risolvibile senza rivedere in toto la realizzazione di top. 
Non pensavo fosse un grosso problema quindi ho lasciato così, temo però di non riuscire a fare di meglio se non usare delle frecce in unicode al posto di top e rinunciare all'attuale aspetto grafico. Se qualcuno ha qualche idea migliore/più bella graficamente sono a braccia aperte XD

**Comment by Penaz91** [comment]
Penso il problema sia risolvibile portando l'aspetto grafico da "div#top" a "div#top a", con i dovuti cambiamenti, ovviamente.
Una prova su firefox sembra funzionare tutto (a parte l'hover che non lo trovo)

**Comment by Rei2229** [comment]
Vedrò che riesco a fare questo pomeriggio allora. Se proprio non riesco chiederò una mano :D
