### ISSUE TITLE
CSS Print

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#5]
Consigli dagli appunti:
- [x] Rimozione immagini non vitali alla comprensione del contenuto
- [x] Rimozione menu
- [x] Rimozione colori (Lo sfondo è rimosso automaticamente dai browser)
- [x] Rimozione banner pubblicitari
- [ ] Rimozione form (A meno che non vengano usati come promemoria per la registrazione
- [x] Impostare l'allineamento a "giustificato"
- [x] Definire la font-size in punti (pt) così che tutte le proprietà "em" si adattino di conseguenza
- [x] Mantenere la width al 100% così che i contenuti occupino tutta la pagina
- [x] Usare font con grazie (Serif, Times, ...)
- [x] Rimozione bordi
- [x] Mantenere le breadcrumb

**Comment by Penaz91** [comment]
Ho aggiunto il tag `<link>` dedicato alla print.
Puoi usare l'emulazione di media type di Chrome per vedere come salta fuori

**Comment by Penaz91** [comment]
Quanto manca per questo?

**Comment by Rei2229** [comment]
A me **pare** di aver fatto tutte le pagine, a parte appunto Noleggio Strumenti che avevo "assegnato" a Fede. Certo sarebbe utile che qualcuno desse un'occhiata se magari va bene/manca qualcosa

**Comment by Penaz91** [comment]
Sono necessarie ulteriori modifiche secondo voi?

**Comment by Penaz91** [comment]
Progetto terminato, chiudo
