### ISSUE TITLE
Inserimento dei TabIndex per I contenuti

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#51]
Il numero di link non è stabile all'interno del sito (Aumentano passando da non-loggato a loggato), questo richiede che uno script PHP vada a generare automaticamente i tabindex dall'alto verso il basso della pagina, per tutti i link ed i bottoni, evitando i link che contengono immagini (penso siano abbastanza inutili per gli screenreader).
Senza di questo probabilmente non riusciremo ad avere un voto decente nella parte di accessibilità.

**Comment by Penaz91** [comment]
@Fomodei94 @Rei2229 @Aronoele20395 Necessito di consulenza.
Secondo questo documento:
https://webaim.org/techniques/keyboard/tabindex
Qualunque scorciatoia con tabindex > 0 viene evidenziata prima di tutti gli elementi senza tabindex o con tabindex negativo, quindi **teoricamente** se mettessimo tabindex statici maggiori di, diciamo... 10, questi dovrebbero essere evidenziati appena dopo il menu, senza dover stare li a contare quanti tabindex sono già occupati.
Come vi sembra come idea?

**Comment by Penaz91** [comment]
L'idea funziona, domanda: dobbiamo rendere tabbabili le breadcrumbs?

**Comment by Fomodei94** [comment]
Secondo me no, rischiamo di allungare e rendere piu' "artificiosa" la navigazione (se ho ben capito cosa intendi, riguardo i tabindex). Chiaramente sentiamo anche gli altri che dicono!
