### ISSUE TITLE
Mancano i tag alt delle immagini nelle pagine

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#52]
Purtroppo molti tag "alt", vitali per la validazione del sito e l'accessibilità, sono mancanti nel sito. È vitale inserirli.

@Rei2229 Qui potrebbe essere necessaria un'ulteriore modifica al DB:
Nella pagina dei noleggi ci sono varie immagini autogenerate che ovviamente mancano del tag "alt", pensi sia sufficiente mettere "Foto <nome della strumentazione>" oppure sia meglio piantare un nuovo campo nel DB in modo da avere qualcosa di più sensato?

**Comment by Rei2229** [comment]
Per "nuovo campo nel DB" intendi un campo "alt"? Per me non ci sarebbero problemi, è una modifica da poco. Forse però a livello didattico che non abbia più senso mettere delle vero foto nell'html col loro tag alt?
Certo che mettendo tutto nel DB sarebbe più carino e versatile però. Fosse per me voterei per inserire un campo nel DB

**Comment by Penaz91** [comment]
A me richiederebbe una modifica nella schermata di inserimento, ricerca e modifica, non da molto ma per ora sono occupato

**Comment by Rei2229** [comment]
Ma no, vai tranquillo. Faccio io una modifica al DB inserendo un campo alt. Poi quando ci sei sfrutti il nuovo campo come meglio credi ;)

**Comment by Penaz91** [comment]
Grazie infinite

**Comment by Rei2229** [comment]
Ma figurati

**Comment by Penaz91** [comment]
Campo completamente implementato nel sito a partire dalla commit 1783e29

**Comment by Aronoele20395** [comment]
A meno che non ci siano immagini nei file PHP, ho fatto pure questo. Chiudo.
