### ISSUE TITLE
LongDesc

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#53]
Le WCAG 2.0 AAA consigliano di usare anche longdesc per una spiegazione lunga (tramite URI) dei contenuti non testuali. Sarebbe carino farlo.
Sempre che non ci siano problemi di sorta.

**Comment by Aronoele20395** [comment]
Dovrei averle fatte tutte, appena riesco a connettere il pc alla rete carico tutto. Intanto chiudo la issue.
