### ISSUE TITLE
Attributi "title" per bottoni e link

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#56]
Secondo xHTML è possibile usare l'attributo "Title" per specificare informazioni aggiuntive riguardo ad un link o bottone, visibile sotto forma di tooltip (suggerimento sotto il mouse) o pronunciabile da uno screenreader. Utili per accessibilità, se non critici.

Questi però non dovrebbero sostituire una buona descrizione dei link

Per i bottoni generati in PHP, ci penso io eventualmente

**Comment by Penaz91** [comment]
Aggiunti tag title autogenerati per la pagina noleggi

**Comment by Aronoele20395** [comment]
Visto che sto già girando tutti i file per sistemare alt e longdesc, tanto vale che mi prenda io l'incarico di aggiungere i titoli. 
Vanno bene cose del tipo "bottone per confermare il noleggio", "link alla pagina di prenotazione" e simili o mi devo impegnare di più? 
Tra parentesi, sto mollando di quelle sviolinate nelle longdesc che Cyrano togliti

**Comment by Penaz91** [comment]
Beh, un po' di più sarebbe meglio.
Tipo "Vai alla pagina di prenotazione"

**Comment by Aronoele20395** [comment]
Se il po' di più è così poco in più, pas des problèmes, ci penso io

**Comment by Aronoele20395** [comment]
Finito. Non dovrebbero essermene sfuggiti. Chiudo.
