### ISSUE TITLE
Linee Guida WCAG 2.0

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#58]
- [x] [Applicazione OPTGROUP all'interno delle select (Magari per sala?)](https://www.w3.org/TR/WCAG20-TECHS/H85.html)
- [x] [Dare un feedback di successo in caso di operazione andata a buon fine](https://www.w3.org/TR/WCAG20-TECHS/G199.html) (Vedi Issue #41)
- [x] [Mettere a disposizione un modo evidente di evidenziare il campo selezionato](https://www.w3.org/TR/WCAG20-TECHS/G195.html)
- [x] [Evidenziare le componenti sotto focus](https://www.w3.org/TR/WCAG20-TECHS/G149.html)
- [x] [Creazione di meccanismi che consentano all'utente di saltare direttamente ad un errore](https://www.w3.org/TR/WCAG20-TECHS/G139.html) (Tipo al campo sbagliato)
- [x] [Aggiungere link alla cima della pagina per ogni sezione del documento](https://www.w3.org/TR/WCAG20-TECHS/G124.html) (Magari come aiuto alla navigazione non visuale, dato che abbiamo il fantastico bottone TOP?)
- [x] [Aggiungere un link all'inizio di aree ripetute per saltarle](https://www.w3.org/TR/WCAG20-TECHS/G123.html)
- [x] [Mettere a disposizione il dato atteso e/o un esempio del formato voluto](https://www.w3.org/TR/WCAG20-TECHS/G89.html) (Sia tramite placeholder che in modo testuale)
- [x] [Mettere a disposizione una mappa del sito](https://www.w3.org/TR/WCAG20-TECHS/G63.html) (Magari anche una in XML come operazione di S.E.O.)
- [x] [Mettere a disposizione link a parole tecniche (anche verso siti esterni)](https://www.w3.org/TR/WCAG20-TECHS/G55.html)
- [x] [Assicurarsi che il contrasto tra testo e sfondo (o sfondo e immagine che sostituisce il testo) sia di almeno 7:1](https://www.w3.org/TR/WCAG20-TECHS/G17.html)
- [x] [Descrivere cosa accade quando l'uso di una form provochi un cambio di contesto prima che questo avvenga](https://www.w3.org/TR/WCAG20-TECHS/G13.html)

**Comment by Penaz91** [comment]
Ho lasciato dei link per @Fomodei94 così da poter far riferimento al WCAG nella relazione

**Comment by Penaz91** [comment]
Contrasto header migliorato nella commit 0c6c4bb

**Comment by Penaz91** [comment]
Ho applicato G149 e G195 di WCAG, ma il bordo di 2 pixel sui link forse non è la scelta ideale per rendere evidente che un link è sotto focus.
Tende a scombinare un po' anche il menu.
Ho evidenziato in giallo il campo in uso, sia esso textbox, description o select, ed è proprio quest'ultimo che da un po' fastidio.
Nel mio browser chrome-based succede questo:
![2018-01-26-192730_1366x768_scrot](https://user-images.githubusercontent.com/6682630/35454608-046d2f30-02cf-11e8-901b-2e9f14f6e6fe.png)
Mentre firefox si comporta bene e mi mostra:
![2018-01-26-192814_1366x768_scrot](https://user-images.githubusercontent.com/6682630/35454621-126d9f84-02cf-11e8-9386-faf7da4caf2d.png)
Che ne pensate?

**Comment by Aronoele20395** [comment]
Secondo me quel giallo si stacca troppo dal resto della pagina, lo sostituirei con una tonalita' di arancione chiaro, magari la stessa che evidenzia le voci di menu' al passaggio del mouse

**Comment by Penaz91** [comment]
Ora provo a vedere cosa sta succedendo, cambio il colore in #FF3300 e cambio il colore al passaggio del mouse.

**Comment by Penaz91** [comment]
@Aronoele20395 Ho modificato il tutto, i campi arancio mi sembra che rendano poco evidenti le scritte (anche se il contrasto è 7.15:1 con #FF6600).
Ho modificato il css del menu così che le voci login, amministrazione e lingua siano evidenziate in modo analogo alle altre voci di menu, però i padding rendono il tutto (secondo me) brutto a vedersi.
Ho evidenziato la parte interessata dai cambiamenti con un commento /* ELE */

**Comment by Penaz91** [comment]
Per la verifica finale: https://www.w3.org/WAI/WCAG20/quickref

**Comment by Penaz91** [comment]
Dichiaro la chiusura a causa della vicinanza della data di consegna. Questo ticket può essere usato come riferimento per la relazione @Fomodei94
