### ISSUE TITLE
La magna ristrutturazione del Sacro Toolkit™

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#60]
Toolkit.php, per quanto utile e carino sta diventando pieno zeppo di codice duplicato, stessa cosa vale per jsToolkit.js e soprattutto dbconn.php

Questo ticket serve solo per tracciare la "Magna Ristrutturazione del Sacro Toolkit™" che avverrà domani, 27 gennaio.

**Comment by Aronoele20395** [comment]
Okionontocconiente *fugge*
