### ISSUE TITLE
Difetto Modifica Strumentazione

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#61]
Sembra che la pagina di modifica strumentazione non accetti i cambiamenti (Almeno per quanto concerne gli alt)

**Comment by Aronoele20395** [comment]
non ho ben capito il problema

**Comment by Penaz91** [comment]
Se provi ad utilizzare la funzione di modifica della strumentazione e modifichi il campo "Alt" di uno strumento, sembra che la modifica non venga salvata

**Comment by Penaz91** [comment]
Per qualche motivo piazza un bello 0 nella parte dell'alt quando modifico uno strumento
