### ISSUE TITLE
Basso contrasto riportato nei link

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#66]
L'analizzatore automatizzato WAVE (http://wave.webaim.org) riporta un contrasto fallimentare (3.44:1) nella parte di login (Link di registrazione), sarebbe meglio prenderci cura di questo problema scurendo lo sfondo o cambiando il meccanismo con cui è costruita la pagina di login/registrazione.

Il contrasto dovrebbe essere almeno di 4.5:1 per il testo piccolo (WCAG AA) o per il testo grande (WCAG AAA)

**Comment by Penaz91** [comment]
Una ristrutturazione delle pagine di dialogo (login, etc...) potrebbe aiutare con i problemi di spazio nel mobile

**Comment by Aronoele20395** [comment]
![schermata del 2018-01-31 18-40-15](https://user-images.githubusercontent.com/35222366/35638039-4c144cb6-06b6-11e8-9246-70327738c4a3.png)
Questa viene bene ma...
![schermata del 2018-01-31 18-40-48](https://user-images.githubusercontent.com/35222366/35638058-5e5d6a2e-06b6-11e8-8e6a-dd48f28bb728.png)
Questa perde qualsiasi dettaglio arancione.
Suggerimenti?

**Comment by Penaz91** [comment]
Io proverei a mettere il titolo arancio

**Comment by Penaz91** [comment]
Riaperto temporaneamente come promemoria per i link arancioni in registrazione_ok.html e registrazione_ko.html

**Comment by Penaz91** [comment]
Confermati messi a posto, chiudo
