### ISSUE TITLE
<legend> Nelle form

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#67]
È consigliato usare i tag <legend> all'interno dei fieldset per dare all'utente un'idea di cosa hanno a che fare certi campi. (Di nuovo, accessibilità)
Questo richiede una piccola ristrutturazione delle form, ma soprattutto un'aggiunta di regole CSS per una corretta visualizzazione delle legends.

In più è ciccia per @Fomodei94 :smile_cat:

**Comment by Aronoele20395** [comment]
Per favore qualcuno controlli se ci sono errori che mi sono persa. Dato che ci siete anche una letta ai paragrafi di istruzioni corrispondenti non sarebbe male, così mi dite cosa fa schifo e cosa tenere.
