### ISSUE TITLE
Traduzione messaggi dal Database

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#71]
Forse sarebbe meglio che il database ritornasse dei codici d'errore piuttosto che dei messaggi, altrimenti non si riuscirebbe ad operarne una traduzione efficiente.

**Comment by Rei2229** [comment]
Io ti ho preparato cilindro e bachetta. Tocca alla tua magua Dani.
Ah se mi dai uno sguardo alle traduzioni in Inglese sono più tranquillo, sei di gran lunga il migliore con la lingua inglese.

**Comment by Penaz91** [comment]
Ok, la cosa sembra funzionare, ma il numero di messaggi hard-coded e' alto e rendera' il processo di traduzione molto complesso

**Comment by Rei2229** [comment]
Mi dispiace my friend... Ci sono parecchie eccezioni ;)

**Comment by Penaz91** [comment]
Sopravvivero'

**Comment by Penaz91** [comment]
Chiusa da 0f3dcfd
