### ISSUE TITLE
formwrapper & co non applicati nello style login

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#72]
Nella login vengono usati i valori predefiniti del browser per fieldset e legend, quindi le legend sembra una label fuori controllo

**Comment by Aronoele20395** [comment]
Potevi scrivermelo nella issue delle legend, vi avevo chiesto di controllare :)

**Comment by Penaz91** [comment]
Shhhh <-<

**Comment by Aronoele20395** [comment]
Io non so nulla xD

**Comment by Penaz91** [comment]
Confermo funzionante, posso chiudere?
