### ISSUE TITLE
Versione Inglese ha diversi problemi

### ISSUE THREAD

**Issue by Rei2229** [UnipdSurvivors/TecWeb#74]
Nel mentre navigavo il sito in inglese per vedere come tradurre in modo coerente i messaggi di errori del DB ho notato che ci sono diversi problemi.
Prendo ad esempio la pagina "Rent a Room"
1) Non viene visualizzato il logo del sito, solo il suo Alt.
2) La form è mezza in italiano, mezza in inglese. Nello specifico la prima form che controlla la disponibilità è giustamente in inglese. La parte di inserimento prenotazione è invece in IT, così come la tabella delle prenotazioni

**Comment by Penaz91** [comment]
La versione inglese ha bisogno di aggiornamenti, penso sia indietro di tipo
un centinaio di commit

Il 01 feb 2018 12:38 AM, "Rei2229" <notifications@github.com> ha scritto:

**Comment by Penaz91** [comment]
Questo è in parte risolto da  0f3dcfd (quando le traduzioni avverranno) e verrà risolto da #46.
Chiudo per ora
