### ISSUE TITLE
Link Menu Attivo ma selezionato ha colore arancio

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#76]
Questo fa in modo che il link abbia colore arancio su sfondo arancio

**Comment by Penaz91** [comment]
Menu a sinistra e bottone annulla a destra

![screen](https://user-images.githubusercontent.com/6682630/35694872-0054ea56-0783-11e8-91c3-37cd07995d6e.png)

La scritta dovrebbe essere in nero

**Comment by Rei2229** [comment]
In realta' a me in locale il bottone non da assolutamente alcun problema, mentre la scritta appare in giallo grazie alla regola in style.css riga 27 ovvero:
a:hover{
color: yellow;
}

**Comment by Rei2229** [comment]
Anzi in realta' non riesco proprio a capire da dove caspiata arrivi quel colore giallo.....

**Comment by Rei2229** [comment]
Ok modifficando la funzione php che richiama il setup del menu' effettivamente tenendo quella voce di menu' disattiva il colore e' giustamente nero. Ma non riesco proprio a capire come mai, se la si decide di tenere attiva venga settato il colore giallo, non capisco nemmeno da dove arrivi.
Mi dispiace molto ma mi vedo costretto a chiedere aiuto stavolta

**Comment by Penaz91** [comment]
Per avere l'arancio devi:
Navigare verso verificaDisp.php
Cancellare la cache
Dare un f5

Il giallo deriva da un a:visited

Il 02 feb 2018 12:47 AM, "Rei2229" <notifications@github.com> ha scritto:
