### ISSUE TITLE
Cambiare Nomi Bottoni

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#78]
Soprattutto admin panel e userpanel

Prenotazione Strumentazione => Noleggio

Prenotazione Sala => Prenotazione

Assegno ad @Aronoele20395 per trovare i nomi piu' adatti, poi li metto a posto io

**Comment by Aronoele20395** [comment]
Se ti vanno bene i nomi che ho inserito con l'ultima push (circa 5 minuti fa, 23:35), direi che è fatta.

**Comment by Penaz91** [comment]
Confermo l'ok per i nomi dei bottoni e chiudo
