### ISSUE TITLE
Messaggi di errore

### ISSUE THREAD

**Issue by Aronoele20395** [UnipdSurvivors/TecWeb#82]
Si tratta di fare ctrl+x, ctrl+v per far apparire i messaggi di errore o conferma in alto sulle pagine. 
Al momento ho notato il messaggio di errore all'accesso che è quasi invisibile nella sua attuale posizione, inoltre non prende lo style degli altri messaggi di errore. Conformo o lascio così?

**Comment by Penaz91** [comment]
Conforma e direi sposta sotto il logo.

**Comment by Aronoele20395** [comment]
Segnalate se ne vedete altri per favore

**Comment by Penaz91** [comment]
Trovato uno nella prenotazione sale, già fixato

**Comment by Penaz91** [comment]
Spostati Altri messaggi. Penso di poter chiudere
