### ISSUE TITLE
Dove mettere i loghi w3c

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#86]
Dato che validiamo il tutto, dobbiamo mettere i loghi del w3c per CSS, HTML e WAI

Loghi WAI: https://www.w3.org/WAI/WCAG2-Conformance#level-AAA

I loghi CSS e xHTML sono dati alla validazione

**Comment by Aronoele20395** [comment]
Nella maniera più sincera possibile: sono talmente brutti che io non perderei nemmeno tempo a lavorarci e li lascerei lì dove sono. Se siete d'accordo, ovviamente.
![schermata del 2018-02-05 15-06-57](https://user-images.githubusercontent.com/35222366/35809466-fe6d2e16-0a88-11e8-8d90-7d9b093090ea.png)

**Comment by Penaz91** [comment]
Io propongo una modifica CSS:
`.w3c{
    display: none;
}`

**Comment by Aronoele20395** [comment]
Mmmmmh, si ma no xD

**Comment by Penaz91** [comment]
Allora vanno bene lì, ben nascosti
