### ISSUE TITLE
Habemus Linkerum Esternerum!

### ISSUE THREAD

**Issue by Aronoele20395** [UnipdSurvivors/TecWeb#89]
Per la gioia di Fede, metteremo dei link esterni alle definizioni di "mixing", "mastering", ecc ecc.

**Comment by Penaz91** [comment]
Missaggio (Mixing): https://it.wikipedia.org/wiki/Missaggio

**Comment by Aronoele20395** [comment]
In che modo inserisco questi link? In maniera esplicita (ad esempio scrivendo "per saperne di più") o implicita trasformando la parola in un link il cui title sarà una cosa del tipo "clicca per saperne di più"? Occhio però che nel secondo caso potrebbe confondere, magari qualcuno immagina che il link porti ad un'altra pagina del sito e non che sia un link esterno.

**Comment by Penaz91** [comment]
Direi una cosa del tipo
Mastering ([definizione](http://it.wikipedia.org/Wiki/Mastering))

**Comment by Aronoele20395** [comment]
Ottimo. Inserisco i link di Facebook, mi date il via libera?

**Comment by Penaz91** [comment]
Vadi vadi

**Comment by Aronoele20395** [comment]
Link Facebook e link a Wiki inseriti.

**Comment by Penaz91** [comment]
Altra ciccia per Ele, ma questa richiederebbe la generazione di pagine statiche dedicate:
**Ghost Production**: Produzione di musica che è stata creata da un certo artista (o artisti) che non verranno accreditati. Tale musica verrà distrubuita sotto il nome di un altro artista o musicista.

**Beat Making**: Produzione di base ritmica, melodia e campioni per una canzone.

Che sia buona cosa creare un "megapaginone" chiamato "definizioni" con vari ID a cui possiamo fare riferimento?
`<a href="definizioni.php#beatmaking">Beat Making</a>`

**Comment by Aronoele20395** [comment]
Fatto 30 facciamo 31, diceva qualcuno

**Comment by Penaz91** [comment]
Ci penso io allora

**Comment by Penaz91** [comment]
Tutto pronto
