### ISSUE TITLE
Miglioramento Prenotazione Sale

### ISSUE THREAD

**Issue by Penaz91** [UnipdSurvivors/TecWeb#9]
Portare la tabella della prenotazione sale tra il bottone "Verifica Disponibilità" e l'orario di inserimento della prenotazione

**Comment by Aronoele20395** [comment]
Aggiungere link definitivo nella pagina "cosa offriamo"

**Comment by Penaz91** [comment]
Link definitivo?

**Comment by Aronoele20395** [comment]
al momento ho messo solo "link alla pagina di prenotazione", non il link serio
